### ISSUE TITLE
Decorrelating this from Pixi

### ISSUE THREAD

**Issue by skymen** [pixijs/layout#79]
Hi,

I just discovered this repo today and it looks very cool. I've been working on something very similar in the past and planned to use it for Construct 3 in the future. Would I be allowed to clone this and try to rework it to function without the pixi requirement?

If so, I would love some pointers if you have any. Is the layout engine based on something else or is it completely custom? Also how hard do you think it would be to have it work with non Pixi objects?

Thanks in advance for any response :)

**Comment by eehunter** [comment]
Obligatory not legal advice, but this project is under an MIT license. From what you describe, it sounds like what you want to do is completely permissible under this license.
